name: SQLMap Security Scans
on:
  push:
    branches: [main]

jobs:
  sqlmap-scan:
    runs-on: ubuntu-latest
    services:
      strapi:
        # Use locally built image through build context
        image: strapi-app
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - 1337:1337
        options: >-
          --health-cmd "curl -f http://localhost:1337/_health || exit 1"
          --health-interval 10s

      - name: Start Strapi on sqlmapnet
        run: docker run -d --name strapi-container --network host strapi-app

      - run: sleep 10
      - run: curl -X GET http://localhost:1337/admin/auth/register-admin
      
      - name: Scan with sqlmap
        uses: thereisnotime/action-sqlmap@master
        with:
          url: "http://localhost:1337/admin/auth/register-admin"
          additional_args: "--batch --crawl=2 --random-agent --forms --level=5 --risk=3"
