name: Build, Scan, SQLMap Scan
on:
  push:
    branches: [ main ]

jobs:
  scan_sqlmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Strapi image
        run: docker build -t strapi-app .

      - name: Create Docker network
        run: docker network create sqlmapnet

      - name: Start Strapi container
        run: |
          docker run -d \
            --name strapi-container \
            --network sqlmapnet \
            strapi-app
      - run: sleep 10
          
      - name: Run SQLMap scan
        run: |
          docker run --rm \
            --network sqlmapnet \
            paoloo/sqlmap \
            --batch \
            --crawl=2 \
            --random-agent \
            --forms \
            --level=5 \
            --risk=3 \
            --url http://strapi-container:1337/admin/auth/register-admin
