name: SQLMap Security Scans
on:
  push:
    branches: [main]

jobs:
  sqlmap-scan:
    runs-on: ubuntu-latest
    services:
      strapi:
        # Use locally built image through build context
        image: strapi-app
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - 1337:1337
        options: >-
          --health-cmd "curl -f http://localhost:1337/_health || exit 1"
          --health-interval 10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Strapi container
        run: |
          docker ps
          curl -v http://localhost:1337/_health

      - name: SQLMap Scan
        uses: thereisnotime/action-sqlmap@master
        with:
          url: "http://strapi:1337/admin/auth/register-admin"
          additional_args: |
            --batch 
            --crawl=2 
            --random-agent 
            --forms 
            --level=5 
            --risk=3 
            --dbms=postgresql