name: SQLMap DAST Scan

on:
  push:
    branches:
      - main

jobs:
  sqlmap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SQLMap scan
        uses: thereisnotime/action-sqlmap@master
        with:
          url: 'https://strapi-devsecops-2.onrender.com/admin/auth/register-admin'
          additional_args: |
            --batch            # Non-interactive mode
            --crawl=1          # Discover links up to depth 1
            --random-agent     # Rotate User-Agent headers
            --level=3          # Scan intensity level (1-5)
            --risk=2           # Risk factor (1-3)