name: Build, Scan, SQLMap Scan
on:
  push:
    branches: [main]

jobs:
  scan_sqlmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t strapi-app .
      
      - name: Create network
        run: docker network create sqlmapnet

      - name: Start Strapi on sqlmapnet
        run: docker run -d --name strapi-container --network sqlmapnet strapi-app

      - run: sleep 10
      - run: docker ps
      - run: ip addr
      
      - name: Scan with sqlmap
        uses: thereisnotime/action-sqlmap@master
        with:
          url: "http://localhost:1337/admin/auth/register-admin"
          additional_args: "--batch --crawl=2 --random-agent --forms --level=5 --risk=3"