name: Build, Scan, SQLMap Scan
on:
  push:
    branches: [main]

jobs:
  scan_sqlmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t strapi-app .

      - name: Create network
        run: docker network create sqlmapnet

      - name: Start Strapi container on sqlmapnet
        run: docker run -d --name strapi-container --network sqlmapnet strapi-app
      - run: sleep 10

      - name: Scan with sqlmap
        uses: thereisnotime/action-sqlmap@master
        with:
          url: "https://strapi-container:1337"
          additional_args: "--batch --crawl=2 --random-agent --forms --level=5 --risk=3"