name: Build, Scan, SQLMap Scan
on:
  push:
    branches: [main]

jobs:
  scan_sqlmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: strapi-app:latest
          load: true

      - name: Wait for Strapi
        run: sleep 10

      - name: Scan with sqlmap
        uses: thereisnotime/action-sqlmap@master
        with:
          url: "http://127.0.0.1:1337/admin/auth/register-admin"
          additional_args: "--batch --crawl=2 --random-agent --forms --level=5 --risk=3"
