name: Build, Scan, SQLMap Scan
on:
  push:
    branches: [main]

jobs:
  scan_sqlmap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t strapi-app .

      - name: Create network
        run: docker network create sqlmapnet

      - run: sleep 10

      - name: Scan with sqlmap
        uses: thereisnotime/action-sqlmap@master
        with:
          url: "http://strapi-container:1337/admin/auth/register-admin"
          additional_args: "--batch --crawl=2 --random-agent --forms --level=5 --risk=3"

