name: Build, Scan, SQLMap Scan
on:
  push:
    branches: [main]

jobs:
  scan_sqlmap:
    runs-on: ubuntu-latest
    steps:
      - name: Start Strapi on sqlmapnet
        run: |
          docker network create sqlmapnet
          docker run -d --name strapi-container --network sqlmapnet strapi-app
      - run: sleep 10

      - name: Run SQLMap in Docker
        run: |
          docker run --rm \
            --network sqlmapnet \
            sqlmapproject/sqlmap:latest \
            -u http://strapi-container:1337/admin/auth/register-admin \
            --batch --crawl=2 --random-agent --forms --level=5 --risk=3

