name: Terrascan IaC Security Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terrascan:
    name: Run Terrascan Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SARIF output directory
        run: mkdir -p terrascan-output

      - name: Run Terrascan (recursive full scan)
        uses: tenable/terrascan-action@v1.4.1
        with:
          iac_type: terraform
          iac_dir: ./
          only_warn: true                # Ensures the workflow doesn't fail
          sarif_upload: true            # Enables GitHub Security Dashboard integration
          output_format: sarif
          output_file: terrascan-output/terrascan.sarif

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: terrascan-output/terrascan.sarif