name: Terrascan IaC Security Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terrascan:
    name: Run Terrascan Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terrascan CLI
        run: |
          curl -L https://github.com/tenable/terrascan/releases/latest/download/terrascan_linux_amd64 -o terrascan
          chmod +x terrascan
          sudo mv terrascan /usr/local/bin/

      - name: Initialize Terrascan (optional but recommended)
        run: terrascan init || echo "Terrascan init skipped (not required for all scans)"

      - name: Run Terrascan Scan on all IaC files
        run: |
          terrascan scan \
            -d . \
            --output sarif \
            --policy-type all > terrascan-results.sarif

      - name: Upload SARIF file to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: terrascan-results.sarif
          token: ${{ secrets.GITHUB_TOKEN }}
