name: Build, Scan, and DAST
on:
  push:
    branches: [main]

jobs:
  security-scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t strapi-app .

      - name: Create network
        run: docker network create zapnet

      - name: Start Strapi on zapnet
        run: docker run -d --name strapi-container --network zapnet strapi-app
      - run: sleep 10

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://strapi-container:1337'
          alert_on_risk: 3
          fail_action: true

