name: Build, Scan, and DAST
on:
  push:
    branches: [main]

jobs:
  security-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t strapi-app .

      - name: Start Strapi container
        run: |
          docker run -d \
            --name strapi-container \
            -p 1337:1337 \
            strapi-app
          
      - name: Wait for Strapi to be ready
        run: |
          until docker logs strapi-container 2>&1 | grep "Server listening"; do
            echo "Waiting for Strapi to start..."
            sleep 5
          done
          sleep 10  # Extra buffer time

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:1337'
          rules_file_name: 'stapi-scan-rules'
          alert_on_risk: 3  # Medium and above
          fail_action: true
          cmd_options: '-I'