name: Build, Scan, and DAST
on:
  push:
    branches: [main]

jobs:
  security-scanning:
    runs-on: ubuntu-latest
    services:
      strapi:
        image: strapi-app
        ports: ['1337:1337']
    steps:
      - uses: actions/checkout@v4
      - name: Wait for Strapi
        run: sleep 10
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://strapi:1337'   # service name as hostname
          alert_on_risk: 3
          fail_action: true
